# Generated by Django 3.0.4 on 2020-04-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('createDate', models.DateField()),
            ],
        ),
    ]
