# Generated by Django 3.0.4 on 2020-04-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('courses', models.ManyToManyField(to='main_course.Course')),
            ],
        ),
    ]
