name: Build backend (user service) docker images and push to registry

on:
  push:
    branches:
    - master
env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  IMAGE: backend-user
  REGISTRY_HOSTNAME: asia.gcr.io
  SERVICE_NAME: femtogudaki-backend-user
  CI: true
jobs:
  setup-build-publish:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '285.0.1'
        service_account_email: ${{ secrets.GKE_EMAIL }}
        service_account_key: ${{ secrets.GKE_KEY }}
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker
      
    - name: Build
      run: |
        cd backend/user        
        docker build -t "$REGISTRY_HOSTNAME"/"$GKE_PROJECT"/"$IMAGE":"$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" .
    - name: Test
      run: |
        docker run -e TESTING=1 $REGISTRY_HOSTNAME/$GKE_PROJECT/$IMAGE:$GITHUB_SHA /bin/sh -c "python3 manage.py test"

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |
        docker push $REGISTRY_HOSTNAME/$GKE_PROJECT/$IMAGE:$GITHUB_SHA

    - name: Deploy
      run: |
           echo Y | gcloud beta run deploy $SERVICE_NAME \
             --image $REGISTRY_HOSTNAME/$GKE_PROJECT/$IMAGE:$GITHUB_SHA \
             --region asia-northeast1 \
             --platform managed \
             --project $GKE_PROJECT \
             --port 8000 \
             --allow-unauthenticated \
             --update-env-vars PRODUCTION=1

